services:
  seed-node:
    image: mina-node
    build: .
    restart: always
    environment:
      KEY: key0
      # SEED_URL: https://storage.googleapis.com/seed-lists/devnet_seeds.txt
      # SEED_URL: https://storage.googleapis.com/seed-lists/mainnet_seeds.txt
      # SEED_URL: https://storage.googleapis.com/seed-lists/berkeley_seeds.txt
      # SEED_URL: https://storage.googleapis.com/seed-lists/testworld-2-0_seeds.txt
    volumes:
      - ./keys:/keys
      - ./mina-config/daemon.json:/root/.mina-config/daemon.json
    ports:
      - 8310:8302
      - 3001:3085
    # network_mode: "service:firewall"
    # depends_on:
    #   - firewall

  node0:
    image: mina-node
    build: .
    restart: always
    environment:
      KEY: key1
      ADDITONAL_ARGS: '--peer /dns4/seed-node/tcp/8302/p2p/${SEED_NODE}'
    volumes:
      - ./keys:/keys
      - ./mina-config/daemon.json:/root/.mina-config/daemon.json
    ports:
      - 8320:8302
      - 3002:3085
    links:
      - seed-node
    # network_mode: "service:firewall"
    # depends_on:
    #   - firewall

  node1:
    image: mina-node
    build: .
    restart: always
    environment:
      KEY: key2
      ADDITONAL_ARGS: '--peer /dns4/seed-node/tcp/8302/p2p/${SEED_NODE}'
    volumes:
      - ./keys:/keys
      - ./mina-config/daemon.json:/root/.mina-config/daemon.json
    ports:
      - 8330:8302
      - 3003:3085
    links:
      - seed-node
  #   links:
  #     - seed-node

  # firewall:
  #   image: mina-firewall
  #   privileged: true
  #   build: 
  #     dockerfile: Dockerfile.bpf
  #   volumes:
  #     - "/sys/kernel/debug:/sys/kernel/debug"
  #     - "/proc:/proc"
    

  # sandbox-node:
  #   image: minaprotocol/mina-daemon:1.3.0-9b0369c-bullseye-devnet
  #   environment:
  #     MINA_PRIVKEY_PASS: ''
  #     RUN_DEMO: true
  #     EXTRA_FLAGS: ' --insecure-rest-server --open-limited-graphql-port --libp2p-keypair /keys/key0 --block-producer-key /keys/block-key0'
  #   ports:
  #     - 3003:3085
  #   volumes:
  #     - ./keys:/keys 
  #     - ./mina-config/daemon.json:/root/.mina-config/daemon.json