services:
  seed-node:
    image: mina-node
    build: .
    restart: always
    environment:
      KEY: key0
      LIBP2P_PORT: 8310
      # SEED_URL: https://storage.googleapis.com/seed-lists/devnet_seeds.txt
      # SEED_URL: https://storage.googleapis.com/seed-lists/mainnet_seeds.txt
      # SEED_URL: https://storage.googleapis.com/seed-lists/berkeley_seeds.txt
      # SEED_URL: https://storage.googleapis.com/seed-lists/testworld-2-0_seeds.txt
    volumes:
      - ./keys:/keys
      - ./mina-config/daemon.json:/root/.mina-config/daemon.json
    ports:
      - 8310:8310
      - 3001:3085

  node0:
    image: mina-node
    build: .
    restart: always
    environment:
      KEY: key1
      LIBP2P_PORT: 8320
    volumes:
      - ./keys:/keys
      - ./mina-config/daemon.json:/root/.mina-config/daemon.json
    ports:
      - 8320:8320
      - 3002:3085
    links:
      - seed-node